import { Aircraft } from "./types"

// SoCal airport coords (ramp/FBO area)
const VNY = { lat: 34.2098, lng: -118.4897 }  // Van Nuys — the billionaire hub
const LAX = { lat: 33.9502, lng: -118.4085 }
const SAN = { lat: 32.7341, lng: -117.1903 }
const SNA = { lat: 33.6757, lng: -117.8683 }  // John Wayne / Orange County
const BUR = { lat: 34.2007, lng: -118.3585 }  // Hollywood Burbank
const PSP = { lat: 33.8297, lng: -116.5067 }  // Palm Springs
const SBA = { lat: 34.4262, lng: -119.8401 }  // Santa Barbara

export const MOCK_AIRCRAFT: Aircraft[] = [
  // ── AIRBORNE ─────────────────────────────────────────────
  {
    icao24: "a835af",
    tailNumber: "N628TS",
    callsign: "N628TS",
    lat: 33.6500,
    lng: -118.9200,
    altitude: 43000,
    speed: 508,
    heading: 82,
    status: "airborne",
    onGround: false,
    lastSeen: new Date(),
    origin: "AUS",
    destination: "VNY",
    aircraftType: "Gulfstream G650ER",
    owner: {
      name: "Elon Musk",
      title: "CEO of Tesla & SpaceX, owner of X",
      netWorth: "$240B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Elon_Musk",
    },
  },
  {
    icao24: "a4bdf2",
    tailNumber: "N72MZ",
    callsign: "N72MZ",
    lat: 34.1200,
    lng: -119.3500,
    altitude: 38000,
    speed: 470,
    heading: 118,
    status: "airborne",
    onGround: false,
    lastSeen: new Date(),
    origin: "SFO",
    destination: "SNA",
    aircraftType: "Dassault Falcon 900EX",
    owner: {
      name: "Mark Zuckerberg",
      title: "Co-founder & CEO of Meta (Facebook)",
      netWorth: "$210B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Mark_Zuckerberg",
    },
  },
  {
    icao24: "ac3f21",
    tailNumber: "N8FG",
    callsign: "N8FG",
    lat: 33.4800,
    lng: -117.7200,
    altitude: 12500,
    speed: 280,
    heading: 310,
    status: "airborne",
    onGround: false,
    lastSeen: new Date(),
    origin: "SAN",
    destination: "VNY",
    aircraftType: "Gulfstream G450",
    owner: {
      name: "Steven Spielberg",
      title: "Filmmaker, director of Jaws, E.T., Schindler's List",
      netWorth: "$4.7B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Steven_Spielberg",
    },
  },
  {
    icao24: "a1c9e4",
    tailNumber: "N77JN",
    callsign: "N77JN",
    lat: 34.5500,
    lng: -118.1200,
    altitude: 22000,
    speed: 440,
    heading: 198,
    status: "airborne",
    onGround: false,
    lastSeen: new Date(),
    origin: "LAS",
    destination: "SBA",
    aircraftType: "Bombardier Global 7500",
    owner: {
      name: "Jensen Huang",
      title: "Co-founder & CEO of NVIDIA",
      netWorth: "$120B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Jensen_Huang",
    },
  },
  // ── TAXIING ──────────────────────────────────────────────
  {
    icao24: "a7e3b9",
    tailNumber: "N888GL",
    callsign: "N888GL",
    lat: VNY.lat + 0.006,
    lng: VNY.lng + 0.003,
    altitude: 0,
    speed: 14,
    heading: 270,
    status: "taxiing",
    onGround: true,
    lastSeen: new Date(),
    origin: "VNY",
    destination: "HNL",
    aircraftType: "Gulfstream G500",
    owner: {
      name: "George Lucas",
      title: "Creator of Star Wars & Indiana Jones, filmmaker",
      netWorth: "$5.5B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/George_Lucas",
    },
  },
  // ── PARKED ───────────────────────────────────────────────
  {
    icao24: "a00a84",
    tailNumber: "N4AC",
    callsign: "N4AC",
    lat: VNY.lat,
    lng: VNY.lng,
    altitude: 0,
    speed: 0,
    heading: 180,
    status: "parked",
    onGround: true,
    lastSeen: new Date(),
    origin: "SEA",
    aircraftType: "Gulfstream G650ER",
    owner: {
      name: "Jeff Bezos",
      title: "Founder of Amazon, executive chairman",
      netWorth: "$230B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Jeff_Bezos",
    },
  },
  {
    icao24: "a9116e",
    tailNumber: "N823DB",
    callsign: "N823DB",
    lat: SNA.lat,
    lng: SNA.lng,
    altitude: 0,
    speed: 0,
    heading: 90,
    status: "parked",
    onGround: true,
    lastSeen: new Date(),
    origin: "OAK",
    aircraftType: "Gulfstream G650ER",
    owner: {
      name: "Larry Ellison",
      title: "Co-founder & CTO of Oracle Corporation",
      netWorth: "$140B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Larry_Ellison",
    },
  },
  {
    icao24: "a9d6ef",
    tailNumber: "N887WM",
    callsign: "N887WM",
    lat: SAN.lat,
    lng: SAN.lng,
    altitude: 0,
    speed: 0,
    heading: 0,
    status: "parked",
    onGround: true,
    lastSeen: new Date(),
    origin: "SEA",
    aircraftType: "Bombardier BD-700 Global Express",
    owner: {
      name: "Bill Gates",
      title: "Co-founder of Microsoft, philanthropist",
      netWorth: "$110B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Bill_Gates",
    },
  },
  {
    icao24: "a5d7e4",
    tailNumber: "N540W",
    callsign: "N540W",
    lat: SBA.lat,
    lng: SBA.lng,
    altitude: 0,
    speed: 0,
    heading: 270,
    status: "parked",
    onGround: true,
    lastSeen: new Date(),
    aircraftType: "Bombardier Global Express XRS",
    owner: {
      name: "Oprah Winfrey",
      title: "Media executive, philanthropist, talk show host",
      netWorth: "$2.8B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Oprah_Winfrey",
    },
  },
  {
    icao24: "ab4c11",
    tailNumber: "N888DG",
    callsign: "N888DG",
    lat: SBA.lat - 0.003,
    lng: SBA.lng + 0.004,
    altitude: 0,
    speed: 0,
    heading: 180,
    status: "parked",
    onGround: true,
    lastSeen: new Date(),
    origin: "TEB",
    aircraftType: "Gulfstream G650",
    owner: {
      name: "David Geffen",
      title: "Media mogul, co-founder of DreamWorks",
      netWorth: "$9.5B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/David_Geffen",
    },
  },
  {
    icao24: "a2fe83",
    tailNumber: "N1TP",
    callsign: "N1TP",
    lat: LAX.lat,
    lng: LAX.lng,
    altitude: 0,
    speed: 0,
    heading: 90,
    status: "parked",
    onGround: true,
    lastSeen: new Date(),
    origin: "ATL",
    aircraftType: "Gulfstream G550",
    owner: {
      name: "Tyler Perry",
      title: "Actor, director, playwright, studio owner",
      netWorth: "$1.0B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Tyler_Perry",
    },
  },
  {
    icao24: "a6c249",
    tailNumber: "N23RM",
    callsign: "N23RM",
    lat: PSP.lat,
    lng: PSP.lng,
    altitude: 0,
    speed: 0,
    heading: 0,
    status: "parked",
    onGround: true,
    lastSeen: new Date(),
    origin: "LGA",
    aircraftType: "Dassault Falcon 7X",
    owner: {
      name: "Rupert Murdoch",
      title: "Media mogul, founder of News Corp & Fox Corporation",
      netWorth: "$17B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Rupert_Murdoch",
    },
  },
  {
    icao24: "a3d7c0",
    tailNumber: "N550KK",
    callsign: "N550KK",
    lat: BUR.lat,
    lng: BUR.lng,
    altitude: 0,
    speed: 0,
    heading: 0,
    status: "parked",
    onGround: true,
    lastSeen: new Date(),
    origin: "ORD",
    aircraftType: "Bombardier Challenger 650",
    owner: {
      name: "Kim Kardashian",
      title: "Entrepreneur, media personality, founder of SKIMS",
      netWorth: "$1.7B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Kim_Kardashian",
    },
  },
]

// Known jets for live filtering (icao24 → metadata)
// Verify at globe.adsbexchange.com before adding new entries
export const KNOWN_JETS: Record<string, { tailNumber: string; aircraftType: string; owner: Aircraft["owner"] }> = {
  a835af: { tailNumber: "N628TS", aircraftType: "Gulfstream G650ER",           owner: { name: "Elon Musk",        title: "CEO of Tesla & SpaceX",          netWorth: "$240B", nationality: "American", wikipediaUrl: "https://en.wikipedia.org/wiki/Elon_Musk" } },
  a00a84: { tailNumber: "N4AC",   aircraftType: "Gulfstream G650ER",           owner: { name: "Jeff Bezos",       title: "Founder of Amazon",               netWorth: "$230B", nationality: "American", wikipediaUrl: "https://en.wikipedia.org/wiki/Jeff_Bezos" } },
  a9116e: { tailNumber: "N823DB", aircraftType: "Gulfstream G650ER",           owner: { name: "Larry Ellison",    title: "Co-founder & CTO of Oracle",      netWorth: "$140B", nationality: "American", wikipediaUrl: "https://en.wikipedia.org/wiki/Larry_Ellison" } },
  a9d6ef: { tailNumber: "N887WM", aircraftType: "Bombardier BD-700",           owner: { name: "Bill Gates",       title: "Co-founder of Microsoft",          netWorth: "$110B", nationality: "American", wikipediaUrl: "https://en.wikipedia.org/wiki/Bill_Gates" } },
  a8097c: { tailNumber: "N72MZ",  aircraftType: "Dassault Falcon 900EX",       owner: { name: "Mark Zuckerberg",  title: "Co-founder & CEO of Meta",         netWorth: "$210B", nationality: "American", wikipediaUrl: "https://en.wikipedia.org/wiki/Mark_Zuckerberg" } },
  a5d7e4: { tailNumber: "N540W",  aircraftType: "Bombardier Global Express XRS", owner: { name: "Oprah Winfrey",  title: "Media executive, philanthropist",  netWorth: "$2.8B", nationality: "American", wikipediaUrl: "https://en.wikipedia.org/wiki/Oprah_Winfrey" } },
}
