import { Yacht } from "./types"

export const MOCK_YACHTS: Yacht[] = [
  // San Diego area
  {
    mmsi: "338234567",
    name: "RISING SUN",
    flag: "🇺🇸",
    length: 138,
    lat: 32.7157,
    lng: -117.1611,
    speed: 0,
    heading: 220,
    status: "moored",
    lastSeen: new Date(),
    destination: "San Diego",
    callsign: "WDG3421",
    builtYear: 2004,
    builder: "Lurssen",
    owner: {
      name: "David Geffen",
      title: "Media mogul, co-founder of DreamWorks",
      netWorth: "$9.5B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/David_Geffen",
    },
  },
  {
    mmsi: "319045600",
    name: "AQUILA",
    flag: "🇰🇾",
    length: 62,
    lat: 32.6980,
    lng: -117.2200,
    speed: 8.2,
    heading: 310,
    status: "underway",
    lastSeen: new Date(),
    destination: "Ensenada",
    callsign: "ZCAT4",
    builtYear: 2011,
    builder: "Feadship",
    owner: {
      name: "Larry Ellison",
      title: "Co-founder & CTO of Oracle Corporation",
      netWorth: "$140B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Larry_Ellison",
    },
  },
  {
    mmsi: "235098765",
    name: "SERENE",
    flag: "🇬🇧",
    length: 134,
    lat: 32.7350,
    lng: -117.1750,
    speed: 0,
    heading: 180,
    status: "anchored",
    lastSeen: new Date(),
    destination: "San Diego",
    callsign: "2BQR7",
    builtYear: 2011,
    builder: "Fincantieri",
    owner: {
      name: "Mohammed bin Salman",
      title: "Crown Prince of Saudi Arabia",
      netWorth: "$700B+",
      nationality: "Saudi Arabian",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Mohammed_bin_Salman",
    },
  },
  {
    mmsi: "248034500",
    name: "OCTOPUS",
    flag: "🇲🇹",
    length: 126,
    lat: 32.6750,
    lng: -117.2450,
    speed: 5.1,
    heading: 45,
    status: "underway",
    lastSeen: new Date(),
    destination: "San Diego",
    callsign: "9HXY1",
    builtYear: 2003,
    builder: "Lurssen",
    owner: {
      name: "Paul Allen Estate",
      title: "Co-founder of Microsoft (estate-owned)",
      netWorth: "$28B (at time of death)",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Paul_Allen",
    },
  },
  {
    mmsi: "311044100",
    name: "KORU",
    flag: "🇧🇸",
    length: 127,
    lat: 32.7100,
    lng: -117.1900,
    speed: 0,
    heading: 90,
    status: "moored",
    lastSeen: new Date(),
    callsign: "C6DT9",
    builtYear: 2023,
    builder: "Oceanco",
    owner: {
      name: "Jeff Bezos",
      title: "Founder of Amazon, executive chairman",
      netWorth: "$230B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Jeff_Bezos",
    },
  },
  // Los Angeles area
  {
    mmsi: "338901234",
    name: "PELORUS",
    flag: "🇺🇸",
    length: 115,
    lat: 33.9800,
    lng: -118.4500,
    speed: 0,
    heading: 270,
    status: "moored",
    lastSeen: new Date(),
    destination: "Marina del Rey",
    callsign: "WXK8821",
    builtYear: 2003,
    builder: "Lurssen",
    owner: {
      name: "Roman Abramovich",
      title: "Billionaire businessman and former owner of Chelsea FC",
      netWorth: "$13B",
      nationality: "Russian-Israeli",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Roman_Abramovich",
    },
  },
  {
    mmsi: "319088712",
    name: "ECLIPSE",
    flag: "🇰🇾",
    length: 162,
    lat: 33.7350,
    lng: -118.2800,
    speed: 6.4,
    heading: 195,
    status: "underway",
    lastSeen: new Date(),
    destination: "San Diego",
    callsign: "ZCBR2",
    builtYear: 2010,
    builder: "Blohm+Voss",
    owner: {
      name: "Roman Abramovich",
      title: "Billionaire businessman and former owner of Chelsea FC",
      netWorth: "$13B",
      nationality: "Russian-Israeli",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Roman_Abramovich",
    },
  },
  {
    mmsi: "235112233",
    name: "AQUA",
    flag: "🇬🇧",
    length: 58,
    lat: 33.7600,
    lng: -118.2100,
    speed: 0,
    heading: 90,
    status: "anchored",
    lastSeen: new Date(),
    destination: "Long Beach",
    callsign: "2CXP4",
    builtYear: 2021,
    builder: "Sinot",
    owner: {
      name: "Bill Gates",
      title: "Co-founder of Microsoft, philanthropist",
      netWorth: "$110B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Bill_Gates",
    },
  },
  {
    mmsi: "248077600",
    name: "NOMAD",
    flag: "🇲🇹",
    length: 36,
    lat: 33.3900,
    lng: -118.4100,
    speed: 7.8,
    heading: 320,
    status: "underway",
    lastSeen: new Date(),
    destination: "Marina del Rey",
    callsign: "9HYZ3",
    builtYear: 2016,
    builder: "Heesen",
    owner: {
      name: "Elon Musk",
      title: "CEO of Tesla and SpaceX, owner of X",
      netWorth: "$240B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Elon_Musk",
    },
  },
  // Santa Barbara area
  {
    mmsi: "338445566",
    name: "SUSSURRO",
    flag: "🇺🇸",
    length: 47,
    lat: 34.4050,
    lng: -119.6900,
    speed: 0,
    heading: 180,
    status: "moored",
    lastSeen: new Date(),
    destination: "Santa Barbara",
    callsign: "WZR4421",
    builtYear: 2008,
    builder: "Perini Navi",
    owner: {
      name: "Oprah Winfrey",
      title: "Media executive, talk show host, philanthropist",
      netWorth: "$2.8B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Oprah_Winfrey",
    },
  },
  {
    mmsi: "319201134",
    name: "HERE COMES THE SUN",
    flag: "🇰🇾",
    length: 55,
    lat: 34.3800,
    lng: -119.9200,
    speed: 4.2,
    heading: 115,
    status: "underway",
    lastSeen: new Date(),
    destination: "Santa Barbara",
    callsign: "ZCFA9",
    builtYear: 2006,
    builder: "Codecasa",
    owner: {
      name: "George Lucas",
      title: "Filmmaker, creator of Star Wars and Indiana Jones",
      netWorth: "$5.5B",
      nationality: "American",
      wikipediaUrl: "https://en.wikipedia.org/wiki/George_Lucas",
    },
  },
  {
    mmsi: "235445566",
    name: "MADSUMMER",
    flag: "🇬🇧",
    length: 93,
    lat: 34.4200,
    lng: -120.0000,
    speed: 0,
    heading: 270,
    status: "anchored",
    lastSeen: new Date(),
    destination: "Channel Islands",
    callsign: "2DXQ1",
    builtYear: 2017,
    builder: "Lurssen",
    owner: {
      name: "James Packer",
      title: "Australian billionaire, media and casino magnate",
      netWorth: "$4.2B",
      nationality: "Australian",
      wikipediaUrl: "https://en.wikipedia.org/wiki/James_Packer",
    },
  },
]
